apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment-red
  labels:
    app: webapp
    color: red
    type: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
      color: red
      type: deployment
  template:
    metadata:
      labels:
        app: webapp
        color: red
        type: deployment
    spec:
      containers:
      - name: webapp
        image: akslab88lu9i.azurecr.io/webapp-color:broken
        env:
        - name: APP_COLOR
          value: red
        ports:
        - name: web
          containerPort: 8080
          protocol: TCP
      terminationGracePeriodSeconds: 5
