apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
  name: webapp
spec:
  clusterIP: 10.0.27.125
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: webapp
    type: deployment
  type: ClusterIP